# Directory to store the statistics in [string]
statsDir = "/tmp/dtnproxy/stats/"

[dtn]
# dtnd details
dtndAddress = "127.0.0.1"
dtndPort = 3000

# URI with dtn scheme [string]
remoteNodeId = "dtn://node1"

# Bundle lifetime in seconds [int]
lifetime = 300


[ros]
# Format:
# [topicName, msgType, [profile]]

# Topics to subscribe to
sub = [
    ["/temperature", "sensor_msgs/msg/Temperature", "test"],
    ["/humidity", "sensor_msgs/msg/RelativeHumidity"],
    ["/detectedImages", "sensor_msgs/msg/Image", "img",],
    ]

# Topics to publish
pub = [
    ["/detectedImages", "sensor_msgs/msg/Image", "imde"],
    ["/temperature", "sensor_msgs/msg/Temperature", "de"],
    ]

# Services to provide
# servers = [
#     ["/add_two_ints", "example_interfaces/srv/AddTwoInts"]
#     ]

# Services to listen to
# clients = [
#     ["/add_two_ints", "example_interfaces/srv/AddTwoInts"]
#     ]


# optimization profiles
[[profile]]
name = "test"

    # [[profile.module]]
    # name = "RateLimit"
    # params = ["10"]

    # [[profile.module]]
    # name = "Logging"
    # params = []

    [[profile.module]]
    name = "Compress"
    params = []

    [[profile.module]]
    name = "Expire"
    params = []

[[profile]]
name = "de"

    [[profile.module]]
    name = "Decompress"
    params = []

    # [[profile.module]]
    # name = "ImageDecompress"
    # params = []

[[profile]]
name = "imde"

    # [[profile.module]]
    # name = "Decompress"
    # params = []

    [[profile.module]]
    name = "ImageDecompress"
    params = []

[[profile]]
name = "img"

    [[profile.module]]
    name = "ImageCompress"
    params = []
