# Directory to store the statistics in [string]
statsDir = "/tmp/dtnproxy/stats/"

[dtn]
# dtnd details
dtndAddress = "127.0.0.1"
dtndPort = 3000

# URI with dtn scheme [string]
remoteNodeId = "dtn://node1"

# Bundle lifetime in minutes [int]
lifetime = 5


[ros]
# Format:
# [topicName, msgType, [profile]]

# Topics to subscribe to
sub = [
    ["/temperature", "sensor_msgs/msg/Temperature", "test"],
    ["/humidity", "sensor_msgs/msg/RelativeHumidity"]
    ]

# Topics to publish
# pub = [
#     ["test", "geometry_msgs/msg/PoseStamped"],
#     ["echo", "geometry_msgs/msg/PoseStamped"]
#     ]

# Services to provide
# servers = [
#     ["/add_two_ints", "example_interfaces/srv/AddTwoInts"]
#     ]

# Services to listen to
# clients = [
#     ["/add_two_ints", "example_interfaces/srv/AddTwoInts"]
#     ]


# optimization profiles
[[profile]]
name = "test"

    [[profile.module]]
    name = "RateLimit"
    params = ["10"]

    # [[profile.module]]
    # name = "RateLimit2"
    # params = ["104", "1"]

