[dtn]
#dtnd details
dtndAddress = "127.0.0.1"
dtndPort = 3000

# URI with dtn scheme [string]
remoteNodeId = "dtn://node1"

# Bundle lifetime in minutes [int]
lifetime = 5


[ros]
# Format:
# [topicName, msgType]

# Topics to subscribe to
sub = [
    ["test", "geometry_msgs/msg/PoseStamped"],
    ["bla", "std_msgs/msg/String"]
    ]

# Topics to publish
pub = [
    ["test", "geometry_msgs/msg/PoseStamped"],
    ["echo", "geometry_msgs/msg/PoseStamped"]
    ]
