[dtn]
# URI with dtn scheme [string]
remoteNodeId = "dtn://node1"

# Bundle lifetime in minutes [int]
lifetime = 5


[ros]
# Format:
# [topicName, msgType]

# Topics to subscribe to
sub = [
    ["test", "geometry_msgs/msg/PoseStamped"],
    ["bla", "std_msgs/msg/String"]
    ]

# Topics to publish
pub = [["echo", "geometry_msgs/msg/PoseStamped"]]
